name: food_delivery_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dots_indicator: ^1.2.0
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  pinput: ^0.2.6
  cloud_firestore: ^0.14.4
  provider: ^4.3.2+3
  geolocator: ^6.1.13
  google_maps_flutter: ^1.0.6
  geocoder: ^0.2.1
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+4
  carousel_slider: ^2.3.1
  paginate_firestore: ^0.2.2
  persistent_bottom_nav_bar: ^3.1.0
  url_launcher: ^5.7.10
  map_launcher: ^1.1.3+1
  expandable_text: ^1.2.0
  flutter_easyloading: ^2.2.2
  toggle_bar: ^1.0.0
  dotted_border: ^1.0.7
  chips_choice: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


  fonts:
    - family: Lato
      fonts:
         - asset: fonts/Lato-Bold.ttf
           weight: 700
         - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
         - asset: fonts/Anton-Regular.ttf


